package com.kimi.proxy.android.ui.theme

import androidx.compose.ui.graphics.Color

// Material You 3 Expressive baseline palette.
// These are used as fallback when dynamic color is unavailable (API < 31).

// Light scheme
val md_primary = Color(0xFF4A66B8)
val md_onPrimary = Color(0xFFFFFFFF)
val md_primaryContainer = Color(0xFFDCE1FF)
val md_onPrimaryContainer = Color(0xFF001550)
val md_secondary = Color(0xFF5A5D72)
val md_onSecondary = Color(0xFFFFFFFF)
val md_secondaryContainer = Color(0xFFDFE0F9)
val md_onSecondaryContainer = Color(0xFF171A2C)
val md_tertiary = Color(0xFFB58F00)
val md_onTertiary = Color(0xFFFFFFFF)
val md_tertiaryContainer = Color(0xFFFFEFA1)
val md_onTertiaryContainer = Color(0xFF372B00)
val md_error = Color(0xFFBA1A1A)
val md_onError = Color(0xFFFFFFFF)
val md_errorContainer = Color(0xFFFFDAD6)
val md_onErrorContainer = Color(0xFF410002)
val md_background = Color(0xFFFEFBFF)
val md_onBackground = Color(0xFF1B1B1F)
val md_surface = Color(0xFFFEFBFF)
val md_onSurface = Color(0xFF1B1B1F)
val md_surfaceVariant = Color(0xFFE2E1EC)
val md_onSurfaceVariant = Color(0xFF45464F)
val md_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_surfaceContainerLow = Color(0xFFF5F3FA)
val md_surfaceContainer = Color(0xFFEFEEF4)
val md_surfaceContainerHigh = Color(0xFFE9E8EE)
val md_surfaceContainerHighest = Color(0xFFE3E2E9)
val md_outline = Color(0xFF767680)
val md_outlineVariant = Color(0xFFC6C5D0)

// Dark scheme
val md_primary_dark = Color(0xFFB8C4FF)
val md_onPrimary_dark = Color(0xFF00277D)
val md_primaryContainer_dark = Color(0xFF2A3F95)
val md_onPrimaryContainer_dark = Color(0xFFDCE1FF)
val md_secondary_dark = Color(0xFFC2C4DD)
val md_onSecondary_dark = Color(0xFF2C2F42)
val md_secondaryContainer_dark = Color(0xFF424559)
val md_onSecondaryContainer_dark = Color(0xFFDFE0F9)
val md_tertiary_dark = Color(0xFFFFE27D)
val md_onTertiary_dark = Color(0xFF5B4500)
val md_tertiaryContainer_dark = Color(0xFF836700)
val md_onTertiaryContainer_dark = Color(0xFFFFEFA1)
val md_error_dark = Color(0xFFFFB4AB)
val md_onError_dark = Color(0xFF690005)
val md_errorContainer_dark = Color(0xFF93000A)
val md_onErrorContainer_dark = Color(0xFFFFDAD6)
val md_background_dark = Color(0xFF121318)
val md_onBackground_dark = Color(0xFFE4E1E9)
val md_surface_dark = Color(0xFF121318)
val md_onSurface_dark = Color(0xFFE4E1E9)
val md_surfaceVariant_dark = Color(0xFF45464F)
val md_onSurfaceVariant_dark = Color(0xFFC6C5D0)
val md_surfaceContainerLowest_dark = Color(0xFF0D0E13)
val md_surfaceContainerLow_dark = Color(0xFF1B1B1F)
val md_surfaceContainer_dark = Color(0xFF1F1F23)
val md_surfaceContainerHigh_dark = Color(0xFF292A2E)
val md_surfaceContainerHighest_dark = Color(0xFF343539)
val md_outline_dark = Color(0xFF90909A)
val md_outlineVariant_dark = Color(0xFF45464F)

// Expressive accent colors (M3 Expressive)
val expressive_yellow = Color(0xFFFFD54F)
val expressive_pink = Color(0xFFFF7B9C)
val expressive_green = Color(0xFF6BCB77)
val expressive_blue = Color(0xFF4D96FF)
